### ISSUE TITLE
Set up a correct Docker-compose

### ISSUE THREAD

**Issue by AshP-dev** [AMAPAD/WolfLease#2]
The current configuration of docker-compose only has specifications for the Dockerfile in the '/api' folder. We need to modify it to include the specifications from the Dockerfile in the '/frontend' folder.

**Comment by AnishMulay** [comment]
The frontend was unable to connect to the backend API because it was configured to use localhost as the base URL. When running the frontend in a Docker container, localhost refers to the container's own internal network, not the host machine or other services.

**Comment by AnishMulay** [comment]
To fix this, the frontend needs to communicate with the backend using the service name defined in the docker-compose.yml file (api) instead of localhost. Docker Compose provides automatic DNS resolution for services within the same network, allowing them to connect using their service names.

Changes Made:

Updated the frontend's environment variable for the base URL to point to http://django_backend:8000 instead of http://localhost:8000.
Ensured both frontend and backend services are on the same Docker network.
This ensures proper communication between the containers and resolves the connectivity issue.
